language: node_js
node_js:
  - "0.10"

script: "./node_modules/.bin/grunt js-unit-test doc publish-doc"

cache:
  directories:
    - node_modules
    - .grunt

deploy:
  provider: nodejitsu
  user: "limikael"
  api_key: "b26bb645-3c25-446c-816a-6efcff78ef7c"